### ISSUE TITLE
'msgpack' distribution was not found error

### ISSUE THREAD

**Issue by itsvenu** [simonvh/genomepy#24]
Hi,

I was trying to use `gimmeMotif` tool and I tried to install `hg19` annotaions with `genomepy`. But unfortunately it is giving me the following error even though I installed `msgpack`

`pkg_resources.DistributionNotFound: The 'msgpack' distribution was not found and is required by genomepy`

Is there anything I am missing here? I installed gimmeMotif tool with `conda`. I'm using `Miniconda2`. When I use gimmeMotif command, e.g.

`gimme maelstrom test.bed hg19 test.gimme.out`

It says

`ValueError: No index found for genome hg19! Has GimmeMotifs been configured correctly and is the genome indexed?
`

Any help would be highly appreciated.

Thank you.

**Comment by simonvh** [comment]
Sorry for the delay! I was away from work the last week.

The  msgpack error is annoying and has to do with some kind of package name mismatch. I haven't been able to solve this in the package. You should be able to fix it with a  `pip install msgpack` in your conda environment.

Second question: I guess that genomepy didn't work and that you have hg19 downloaded via other means? In that case you should be be able to specify the location (full path) of the hg19 FASTA file instead of `hg19` and that should work. (you are using the latest version of GimmeMotifs, 0.12.0, right?)

**Comment by itsvenu** [comment]
Hi Simon,

Thanks for the reply. I've installed `msgpack` via `conda`. Is it mandatory to install it through `pip`?

Second question: Yes, I already have hg19 FASTA file, so I didn't download it again with genomepy. I will try specifying the FASTA file path.

Thank you.

**Comment by simonvh** [comment]
Yeah, I know that it is installed via conda (it is one of the dependencies), however, somehow it is not picked up. By installing it through pip the issue is solved.

**Comment by itsvenu** [comment]
Thank you. I will try installing with pip.

**Comment by simonvh** [comment]
Just for your information, the newest release of genomepy (0.5.2) does not have this troublesome dependency on msgpack anymore.
