### ISSUE TITLE
urllib2 missing from requirements in setup.py

### ISSUE THREAD

**Issue by endrebak** [simonvh/genomepy#3]
Also, cannot find urllib2 in pip:

```bash
endrebas@D-174167-DHCP /m/l/h/e/g/rn6> pip install genomepy
Collecting genomepy
  Downloading genomepy-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wu8o7cjq/genomepy/setup.py", line 3, in <module>
        import genomepy
      File "/tmp/pip-build-wu8o7cjq/genomepy/genomepy/__init__.py", line 4, in <module>
        from genomepy.provider import ProviderBase
      File "/tmp/pip-build-wu8o7cjq/genomepy/genomepy/provider.py", line 6, in <module>
        import urllib2
    ModuleNotFoundError: No module named 'urllib2'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wu8o7cjq/genomepy/

endrebas@D-174167-DHCP /m/l/h/e/g/rn6> pip install urllib2
Collecting urllib2
  Could not find a version that satisfies the requirement urllib2 (from versions: )
No matching distribution found for urllib2
```

**Comment by simonvh** [comment]
This is an issue where I did not correctly support python 3. It's fixed in the current develop branch. I'll try to release this version soon, but in the meanwhile you can either use python 2, or install the development version to use with Python 3:

```
$ pip install git+https://github.com/simonvh/norns.git@develop
$ pip install git+https://github.com/simonvh/genomepy.git@develop
```

There is a small change in this version, which is where the genome files will be stored. Instead of providing this at the command line it's specified in the config file  `~/.config/genomepy/genomepy.yaml`:

```
genome_path: ~/genomes
```

Although I am using `genomepy` myself, it's still somewhat immature. So if you encounter any issues please let me know. And thanks for trying it :).

**Comment by endrebak** [comment]
Thanks. I think genomepy is a brilliant idea. When it is more mature it should be added to bioconda. It will somewhat simplify/streamline pipelines where the first step is downloading a (potentially) missing genome to index and then align against.

**Comment by endrebak** [comment]
And I think being able to specify where the file should be stored should be a command line flag that can overwrite the config. If I want to use genomepy in a script made for others, they should not have to know anything about genomepy or its internals, but they will have to if you require a config file. I cannot use it if you require a config file.

**Comment by simonvh** [comment]
I agree, makes sense. I'll fix that.

**Comment by simonvh** [comment]
See #5.
